### ISSUE TITLE
Tests are useless

### ISSUE THREAD

**Issue by ghost** [geckoboard/geckoboard-node#11]
Most of the tests test the wrong thing. For example:
https://github.com/geckoboard/geckoboard-node/blob/bbce7f1e41e939a0996f86337e4cb1bf9bd47613/lib/datasets-test.js#L16

In your documentation there is no `datAtime` type. But based on this:

> For example, attempting to store a number in a datetime field will result in an error.

I'm guessing using a wrong field type would result in an error too, but the test case returns success.

The problem here is that this is not the right way of mocking (or `nock`ing) http requests. And the biggest problem is that only the success state is tested, and only by checking if `nock` returns the data you set to it, which I'm quite sure will always be true. Most likely the only place you want check that is the `api-request-test`, because now if your API changes you have to change the tests in all of your test files. (By the way why aren't the tests placed in a separate directory?)
And what about error cases? Like wrong type of field data or field type? Most people will be bit by these and right now there are no tests for these at all.

**Comment by carlmw** [comment]
Firstly, opening a PR with the subject "Tests are useless" is an awful way to establish a rapport with a maintainer. Criticism is fine but your tack would put most on the defensive. I'll give you the benefit of the doubt in this case but if you want to get anywhere, i'd suggest you adopt a more diplomatic approach.

> In your documentation there is no datAtime type. But based on this:

Yep thats a typo. That said, the typo does not render the tests invalid.

> I'm guessing using a wrong field type would result in an error too, but the test case returns success.

We've intentionally left error handling up to the server (so that we don't have to maintain two sets of error handling). Errors are handled by `apiRequest` (anything other than a `2xx` response will result in an error being passed to your callback). Since every request we're making goes through `apiRequest` testing the error handling again for each method would be entirely superfluous.

> The problem here is that this is not the right way of mocking (or nocking) http requests. And the biggest problem is that only the success state is tested, and only by checking if nock returns the data you set to it, which I'm quite sure will always be true.

I agree that we shouldn't be using nock at this level (Verification of the network stuff belongs entirely within `api-request-test.js`). However "the biggest problem" is not a problem at all.
The intention of the unit tests in this case is to verify the contract between the API and its dependencies (in this case `apiRequest`). It is entirely enough to verify the happy path since we know that `apiRequest` will surface any errors received from the server. 

> Most likely the only place you want check that is the api-request-test,

💯 

> (By the way why aren't the tests placed in a separate directory?)

We use this approach for all our internal projects. We find it easier to find the specs for a module (especially when deleting stuff when its easy to forget to delete the specs in another directory)

> And what about error cases? Like wrong type of field data or field type? 

Again the server will respond with a `400` response which will result in an error being passed to the callback (with a helpful message from the server)


I'm going to remove nock where appropriate. But thanks for your feedback!

**Comment by bezformy** [comment]
Sorry, I didn't mean it in a rude way, just "useless" was the first word that came to mind when I wrote the issue. English is not my first language, you see. But you are right, I should've used more neutral wording. But I hope my explanation on the issue was not offending. I just think that if something then the tests should be as perfect as possible, because otherwise the code itself can be flawed, and no matter the amount of tests you have if they won't catch an error before it goes to production. That's why I used the word "useless".

Again, I'm sorry for that!
Please give the issue a more appropriate title if you think it's worth keeping it open.

**Comment by bezformy** [comment]
I just remembered something, I was reading this before I opened this issue:
https://github.com/carlmw/livingwithcode/blob/63f70690819d02c79ed9b143375fa672209f95b3/index.html#L109
I guess this had an impact on why I stuck with too harsh wording. (Sorry, one more time.)
