### ISSUE TITLE
Not really a bug, but...

### ISSUE THREAD

**Issue by bezformy** [geckoboard/geckoboard-node#12]
Why is the `delete` function used differently than `findOrCreate` or `ping`? It is the only function defined this way:
https://github.com/geckoboard/geckoboard-node/blob/f7e2413150175b0a460fcc63647424f8a9ce5eb3/lib/index.js#L17

And in the documentation you use this module like this:
```js
const gb = require('geckoboard')(
  '222efc82e7933138077b1c2554439e15'
);
```
But this way there is no way to get the version number, because `gb.VERSION` returns `undefined`. Wouldn't it be better to put it inside the `return` block in the `index.js`?

**Comment by carlmw** [comment]
`delete` is available as a module level function as well as when you're working on a Dataset returned from `findOrCreate`. The public API is consistent. From an implementation perspective we're just applying arguments to the protected `delete` (as imported from `delete.js`). This is so that we can share the same code for the "instance" and module. 

As for the version number this is a deliberate design decision so that customers can create instances of the client for multiple accounts (a genuine need).

```javascript
const gb = require('geckoboard');

console.log(gb.VERSION);
// -> 1.0.0

const account1 = gb('222efc82e7933138077b1c2554439e15');
const account2 = gb('51e9344552c1b7708313397e28cfe222');

// Etc.
```

In the docs its presented as per your example for brevity. If you found this confusing then its possibly a sign that we might need to make this clearer in the docs.
